database:
  type: "sqlite" #mysql
  user: "root"
  password: ""
  host: "localhost"
  database: "test"
  port: 3306
  file: "plugins/MinecraftSolutions/vip.db"

onlineGive: true #true -> player needs to be online to receive VIP; false -> player does not need to be online to receive VIP
chat: true #true -> message in chat for all players when someone activates VIP
title: true #true -> title for all players when someone activates VIP
actionBar: true #true -> actionBar for all players when someone activates VIP
